module.exports = [
  {
    first_name: 'Tytos',
    last_name: 'Lannister',
    gender: 'male',
    dob: 220,
    dod: 267,
    place: 'Casterly Rock',
    placeOfBirth: 'Ashemark',
    parents: '',
    spouses: 'Jeyne Lannister',
    children: 'Tywin Lannister, Kevan Lannister',
  },
  {
    first_name: 'Jeyne',
    last_name: 'Lannister',
    gender: 'female',
    dob: 217,
    dod: 255,
    place: 'Casterly Rock',
    placeOfBirth: 'Casterly Rock',
    parents: '',
    spouses: 'Tytos Lannister',
    children: 'Tywin Lannister, Kevan Lannister',
  },
  {
    first_name: 'Tywin',
    last_name: 'Lannister',
    gender: 'male',
    dob: 242,
    dod: 300,
    place: 'Kings Landing',
    placeOfBirth: 'Casterly Rock',
    parents: 'Tytos Lannister, Jeyne Lannister',
    spouses: 'Joanna Lannister',
    children: 'Jaime Lannister, Cercei Lannister, Tyrion Lannister',
  },
  {
    first_name: 'Joanna',
    last_name: 'Lannister',
    gender: 'female',
    dob: 248,
    dod: 273,
    place: 'Casterly Rock',
    placeOfBirth: 'Casterly Rock',
    parents: '',
    spouses: 'Tywin Lannister',
    children: 'Jaime Lannister, Cercei Lannister, Tyrion Lannister',
  },
  {
    first_name: 'Jaime',
    last_name: 'Lannister',
    gender: 'male',
    dob: 266,
    dod: null,
    place: 'Riverrun',
    placeOfBirth: 'Casterly Rock',
    parents: 'Tywin Lannister, Joanna Lannister',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Cercei',
    last_name: 'Lannister',
    gender: 'female',
    dob: 266,
    dod: null,
    place: 'Kings Landing',
    placeOfBirth: 'Casterly Rock',
    parents: 'Tywin Lannister, Joanna Lannister',
    spouses: 'Robert Baratheon',
    children: 'Joffrey Baratheon, Myrcella Baratheon, Tommen Baratheon',
  },
  {
    first_name: 'Tyrion',
    last_name: 'Lannister',
    gender: 'male',
    dob: 273,
    dod: null,
    place: 'Meereen',
    placeOfBirth: 'Casterly Rock',
    parents: 'Tywin Lannister, Joanna Lannister',
    spouses: 'Tysha, Sansa Stark',
    children: '',
  },
  {
    first_name: 'Kevan',
    last_name: 'Lannister',
    gender: 'male',
    dob: 244,
    dod: 300,
    place: 'Kings Landing',
    placeOfBirth: 'Casterly Rock',
    parents: 'Tytos Lannister, Jeyne Lannister',
    spouses: 'Dorna Swyft',
    children: 'Lancel Lannister, Willem Lannister, Martyn Lannister',
  },
  {
    first_name: 'Dorna',
    last_name: 'Swyft',
    gender: 'female',
    dob: 252,
    dod: null,
    place: 'Casterly Rock',
    placeOfBirth: 'Cornfield',
    parents: '',
    spouses: 'Kevan Lannister',
    children: 'Lancel Lannister, Willem Lannister, Martyn Lannister',
  },
  {
    first_name: 'Lancel',
    last_name: 'Lannister',
    gender: 'male',
    dob: 282,
    dod: null,
    place: 'Kings Landing',
    placeOfBirth: 'Casterly Rock',
    parents: 'Kevan Lannister, Dorna Swyft',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Willem',
    last_name: 'Lannister',
    gender: 'male',
    dob: 286,
    dod: 299,
    place: 'Kings Landing',
    placeOfBirth: 'Casterly Rock',
    parents: 'Kevan Lannister, Dorna Swyft',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Martyn',
    last_name: 'Lannister',
    gender: 'male',
    dob: 286,
    dod: null,
    place: 'Kings Landing',
    placeOfBirth: 'Casterly Rock',
    parents: 'Kevan Lannister, Dorna Swyft',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Hoster',
    last_name: 'Tully',
    gender: 'male',
    dob: 239,
    dod: 300,
    place: 'Riverrun',
    placeOfBirth: 'Riverrun',
    parents: '',
    spouses: 'Minisa Tully',
    children: 'Lysa Arryn, Catelyn Stark, Edmure Tully',
  },
  {
    first_name: 'Brynden',
    last_name: 'Tully',
    gender: 'male',
    dob: 242,
    dod: null,
    place: 'Riverrun',
    placeOfBirth: 'Riverrun',
    parents: '',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Minisa',
    last_name: 'Tully',
    gender: 'female',
    dob: 250,
    dod: 273,
    place: 'Riverrun',
    placeOfBirth: 'Harrenhall',
    parents: '',
    spouses: 'Hoster Tully',
    children: 'Lysa Arryn, Catelyn Stark, Edmure Tully',
  },
  {
    first_name: 'Catelyn',
    last_name: 'Stark',
    gender: 'female',
    dob: 264,
    dod: 299,
    place: 'The Twins',
    placeOfBirth: 'Riverrun',
    parents: 'Hoster Tully, Minisa Tully',
    spouses: 'Eddard Stark',
    children: 'Robb Stark, Sansa Stark, Arya Stark, Bran Stark, Rickon Stark',
  },
  {
    first_name: 'Lysa',
    last_name: 'Arryn',
    gender: 'female',
    dob: 268,
    dod: 300,
    place: 'Eyrie',
    placeOfBirth: 'Riverrun',
    parents: 'Hoster Tully, Minisa Tully',
    spouses: 'Jon Arryn, Petyr Baelish',
    children: 'Robin Arryn',
  },
  {
    first_name: 'Edmure',
    last_name: 'Tully',
    gender: 'male',
    dob: 270,
    dod: null,
    place: 'Riverrun',
    placeOfBirth: 'Riverrun',
    parents: 'Hoster Tully, Minisa Tully',
    spouses: 'Roslin Tully',
    children: '',
  },
  {
    first_name: 'Steffon',
    last_name: 'Baratheon',
    gender: 'male',
    dob: 246,
    dod: 278,
    place: 'Shipbreaker Bay',
    placeOfBirth: 'Storms End',
    parents: '',
    spouses: 'Cassana Estermont',
    children: 'Robert Baratheon, Stannis Baratheon, Renly Baratheon',
  },
  {
    first_name: 'Cassana',
    last_name: 'Estermont',
    gender: 'female',
    dob: 232,
    dod: 278,
    place: 'Shipbreaker Bay',
    placeOfBirth: 'Greenstone',
    parents: '',
    spouses: 'Steffon Baratheon',
    children: '',
  },
  {
    first_name: 'Robert',
    last_name: 'Baratheon',
    gender: 'male',
    dob: 262,
    dod: 298,
    place: 'Kings Landing',
    placeOfBirth: 'Storms End',
    parents: 'Steffon Baratheon, Cassana Estermont',
    spouses: 'Cercei Lannister',
    children: 'Joffrey Baratheon, Myrcella Baratheon, Tommen Baratheon',
  },
  {
    first_name: 'Stannis',
    last_name: 'Baratheon',
    gender: 'male',
    dob: 264,
    dod: null,
    place: 'Winterfell',
    placeOfBirth: 'Storms End',
    parents: 'Steffon Baratheon, Cassana Estermont',
    spouses: 'Selyse Baratheon',
    children: 'Shireen Baratheon',
  },
  {
    first_name: 'Renly',
    last_name: 'Baratheon',
    gender: 'male',
    dob: 277,
    dod: 299,
    place: 'Storms End',
    placeOfBirth: 'Storms End',
    parents: 'Steffon Baratheon, Cassana Estermont',
    spouses: 'Margaery Tyrell',
    children: '',
  },
  {
    first_name: 'Joffrey',
    last_name: 'Baratheon',
    gender: 'male',
    dob: 286,
    dod: 300,
    place: 'Kings Landing',
    placeOfBirth: 'Kings Landing',
    parents: 'Robert Baratheon, Cercei Lannister',
    spouses: 'Margaery Tyrell',
    children: '',
  },
  {
    first_name: 'Myrcella',
    last_name: 'Baratheon',
    gender: 'female',
    dob: 290,
    dod: null,
    place: 'Sunspear',
    placeOfBirth: 'Kings Landing',
    parents: 'Robert Baratheon, Cercei Lannister',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Tommen',
    last_name: 'Baratheon',
    gender: 'male',
    dob: 291,
    dod: null,
    place: 'Kings Landing',
    placeOfBirth: 'Kings Landing',
    parents: 'Robert Baratheon, Cercei Lannister',
    spouses: 'Margaery Tyrell',
    children: '',
  },
  {
    first_name: 'Luthor',
    last_name: 'Tyrell',
    gender: 'male',
    dob: 237,
    dod: 268,
    place: 'Highgarden',
    placeOfBirth: 'Highgarden',
    parents: '',
    spouses: 'Olena Tyrell',
    children: 'Mace Tyrell',
  },
  {
    first_name: 'Olena',
    last_name: 'Tyrell',
    gender: 'female',
    dob: 228,
    dod: null,
    place: 'Kings Landing',
    placeOfBirth: 'Arbor',
    parents: '',
    spouses: 'Luthor Tyrell',
    children: 'Mace Tyrell',
  },
  {
    first_name: 'Mace',
    last_name: 'Tyrell',
    gender: 'male',
    dob: 260,
    dod: null,
    place: 'Kings Landing',
    placeOfBirth: 'Highgarden',
    parents: 'Luthor Tyrell, Olena Tyrell',
    spouses: 'Alerie Tyrell',
    children: 'Loras Tyrell, Margaery Tyrell',
  },
  {
    first_name: 'Alerie',
    last_name: 'Tyrell',
    gender: 'female',
    dob: 261,
    dod: null,
    place: 'Highgarden',
    placeOfBirth: 'Oldtown',
    parents: '',
    spouses: 'Mace Tyrell',
    children: 'Loras Tyrell, Margaery Tyrell',
  },
  {
    first_name: 'Loras',
    last_name: 'Tyrell',
    gender: 'male',
    dob: 282,
    dod: null,
    place: 'Dragonstone',
    placeOfBirth: 'Highgarden',
    parents: 'Mace Tyrell, Alerie Tyrell',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Margaery',
    last_name: 'Tyrell',
    gender: 'female',
    dob: 283,
    dod: null,
    place: 'Kings Landing',
    placeOfBirth: 'Highgarden',
    parents: 'Mace Tyrell, Alerie Tyrell',
    spouses: 'Renly Baratheon, Joffrey Baratheon, Tommen Baratheon',
    children: '',
  },
  {
    first_name: 'Rickard',
    last_name: 'Stark',
    gender: 'male',
    dob: 240,
    dod: 282,
    place: 'Kings Landing',
    placeOfBirth: 'Winterfell',
    parents: '',
    spouses: 'Lyarra Stark',
    children: 'Brandon Stark, Benjen Stark, Eddard Stark, Lyanna Stark',
  },
  {
    first_name: 'Lyarra',
    last_name: 'Stark',
    gender: 'female',
    dob: 235,
    dod: 288,
    place: 'Winterfell',
    placeOfBirth: 'Winterfell',
    parents: '',
    spouses: 'Rickard Stark',
    children: 'Brandon Stark, Benjen Stark, Eddard Stark, Lyanna Stark',
  },
  {
    first_name: 'Brandon',
    last_name: 'Stark',
    gender: 'male',
    dob: 262,
    dod: 282,
    place: 'Kings Landing',
    placeOfBirth: 'Winterfell',
    parents: 'Rickard Stark, Lyarra Stark',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Eddard',
    last_name: 'Stark',
    gender: 'male',
    dob: 263,
    dod: 299,
    place: 'Kings Landing',
    placeOfBirth: 'Winterfell',
    parents: 'Rickard Stark, Lyarra Stark',
    spouses: 'Catelyn Tully',
    children: 'Robb Stark, Sansa Stark, Arya Stark, Bran Stark, Rickon Stark',
  },
  {
    first_name: 'Lyanna',
    last_name: 'Stark',
    gender: 'female',
    dob: 266,
    dod: 283,
    place: 'Princes Pass',
    placeOfBirth: 'Winterfell',
    parents: 'Rickard Stark, Lyarra Stark',
    spouses: 'Rhaegar Targaryen',
    children: 'Jon Snow',
  },
  {
    first_name: 'Benjen',
    last_name: 'Stark',
    gender: 'male',
    dob: 267,
    dod: null,
    place: 'Castle Black',
    placeOfBirth: 'Winterfell',
    parents: 'Rickard Stark, Lyarra Stark',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Jon',
    last_name: 'Snow',
    gender: 'male',
    dob: 283,
    dod: null,
    place: 'Castle Black',
    placeOfBirth: 'Princes Pass',
    parents: 'Rhaegar Targaryen, Lyanna Stark',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Robb',
    last_name: 'Stark',
    gender: 'male',
    dob: 283,
    dod: 299,
    place: 'The Twins',
    placeOfBirth: 'Winterfell',
    parents: 'Eddard Stark, Catelyn Tully',
    spouses: 'Jeyne Westerling',
    children: '',
  },
  {
    first_name: 'Sansa',
    last_name: 'Stark',
    gender: 'female',
    dob: 286,
    dod: null,
    place: 'Eyrie',
    placeOfBirth: 'Winterfell',
    parents: 'Eddard Stark, Catelyn Tully',
    spouses: 'Tyrion Lannister',
    children: '',
  },
  {
    first_name: 'Arya',
    last_name: 'Stark',
    gender: 'female',
    dob: 289,
    dod: null,
    place: 'Braavos',
    placeOfBirth: 'Winterfell',
    parents: 'Eddard Stark, Catelyn Tully',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Bran',
    last_name: 'Stark',
    gender: 'male',
    dob: 290,
    dod: null,
    place: 'Beyond The Wall',
    placeOfBirth: 'Winterfell',
    parents: 'Eddard Stark, Catelyn Tully',
    spouses: '',
    children: '',
  },
  {
    first_name: 'Rickon',
    last_name: 'Stark',
    gender: 'male',
    dob: 295,
    dod: null,
    place: 'Beyond The Wall',
    placeOfBirth: 'Winterfell',
    parents: 'Eddard Stark, Catelyn Tully',
    spouses: '',
    children: '',
  },
];
