FROM node:18-alpine
WORKDIR /gapp

COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

RUN echo node-modules\ndist>.dockerignore
COPY . .
RUN rm .dockerignore
RUN yarn compile

EXPOSE 3000
CMD ["yarn", "start:dev"]