version: '3.3'

services:
  db:
    container_name: postgres
    image: gapp/db
    build: ./postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: gapp-backend
    image: gapp/backend
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  dbdata:
    external: true
