version: '3.3'

services:
  db:
    container_name: postgres
    image: gapp/db
    build: ./postgres
    volumes:
      - gapp-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: gapp-backend
    image: arturasmckwcz/gapp-backend
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: yarn start

volumes:
  gapp-db:
    external: true
