DO $$ 
BEGIN 
  CREATE USER mocha WITH PASSWORD 'mocha' SUPERUSER;
  EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '% skipping', SQLERRM USING ERRCODE = SQLSTATE;

  IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'mocha') THEN
      CREATE DATABASE mocha;
  END IF;
END;
$$;

GRANT ALL PRIVILEGES ON DATABASE mocha TO mocha;