name: Build and push Docker image
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: |
          echo ${{ github }}
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.repository }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        run: |
          PR_DATE_NUMBER=$(echo $(date +'%Y-%m-%d')).${{ github.ref }}
          docker build --build-arg PR_DATE_NUMBER=${PR_DATE_NUMBER} -f build.Dockerfile -t arturasmckwcz/gapp-backend .
          docker push arturasmckwcz/gapp-backend
