name: Build and push Docker image for staging
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR_DATE_NUMBER environment var
        run: |
          PR_DATE_NUMBER=$(echo $(date +'%Y-%m-%d')).$(echo "$GITHUB_REF" | awk 'BEGIN { FS="/" } ; { print $3 }')
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build --build-arg PR_DATE_NUMBER=${PR_DATE_NUMBER} -f build.Dockerfile -t arturasmckwcz/gapp-back-staging .
          docker push arturasmckwcz/gapp-back-staging
