name: Build and push Docker image for staging
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -f build.Dockerfile -t arturasmckwcz/gapp-back-staging .
          docker push arturasmckwcz/gapp-back-staging
